anonymous_ttf_url: "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/AnonymousPro/complete/Anonymice%20Powerline%20Nerd%20Font%20Complete%20Mono.ttf?raw=true"
anonymous_ttf_sha: "sha256:6600d6e6a52a277ced42beb07fd30159847ec89462ff8cf9c221df0775412400"

vim_airline_theme_url: "https://raw.githubusercontent.com/morhetz/gruvbox/master/autoload/airline/themes/gruvbox.vim"
vim_airline_theme_sha: "sha256:84510d8b2a2b94296085dd47afe57bdb3e635f087769fb38673f9261b2601cd6"

vim_plug_url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
vim_plug_sha: "sha256:5bd156688f98dba0b38c115888ef756fa6c5a087a58ee5e3542286d7f99ae3f0"
