#!/usr/bin/env bash

## ~/.bash_profile: executed by bash(1) for login shells (spawned by a TTY or by a SSH daemon)

# XDG base directories
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-{{ .chezmoi.homedir }}/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-{{ .chezmoi.homedir }}/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-{{ .chezmoi.homedir }}/.local/share}"

# If not running interactively, don't do anything else
case $- in
  *i*) ;;
    *) return;;
esac

# Source shared numbered config files
for file in "$XDG_CONFIG_HOME"/shell/[0-9][0-9]_*.sh; do
  [ -r "$file" ] && . "$file"
done

# Source BASH numbered config files
for file in "$XDG_CONFIG_HOME"/bash/[0-9][0-9]_*.bash; do
  [ -r "$file" ] && . "$file"
done

# Message of the Day

# Print pretty system logo/info (neofetch)
if [ "$(command -v neofetch)" ]; then
  neofetch
fi

# Fortune
if [ "$(command -v fortune)" ]; then
  fortune computers science
fi

# Show today's anniversaries
if [ "$(command -v calendar)" ]; then
  calendar -A 0 -f /usr/share/calendar/calendar.world
fi
