#!/usr/bin/env bash

# ~/.bash_profile: executed by bash(1) for login shells (spawned by a TTY or by a SSH daemon)

# If not running interactively, don't do anything
case $- in
  *i*) ;;
  *) return ;;
esac

# If $XDG_CONFIG_HOME is not set, don't do anything else
# shellcheck disable=SC2154
if [ -z "$XDG_CONFIG_HOME" ]; then
  echo 'XDG_CONFIG_HOME not set' && return
fi

# Source BASH numbered config files
for file in "$XDG_CONFIG_HOME"/bash/[0-9][0-9]_*.sh; do
  [ -r "$file" ] && . "$file"
done

# Source shared numbered config files
for file in "$XDG_CONFIG_HOME"/shell/[0-9][0-9]_*.sh; do
  [ -r "$file" ] && . "$file"
done

# Execute Message of the Day script
if [ "$(command -v motd)" ]; then
  motd
fi
