- name: "Pacman: update package cache"
  pacman: update_cache=yes
  when: package_update
  become: true

- name: "Pacman: update packages"
  pacman: upgrade=yes
  when: package_upgrade
  become: true

- name: "Pacman: install packages"
  pacman: name={{item}} state=present
  with_items: '{{pacman_packages}}'
  become: true
