- name: "ArchLinux Pacman : update packages"
  pacman:
    update_cache: yes
    upgrade: yes
  when: package_upgrade
  become: true

- name: "ArchLinux Pacman : install packages"
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ pacman_packages }}"
  become: true

- name: "ArchLinux AUR : cache directory"
  file:
    path: "{{ xdg_cache_home }}/aur"
    state: directory
    mode: 0755

- name: "ArchLinux AUR : install helper"
  aur:
    name: "{{ aur_helper }}"
    dir:  "{{ xdg_cache_home }}/aur"
    user: "{{ ansible_user_id }}"
    skip_pgp: yes
  become: true

- name: "ArchLinux AUR : install packages"
  aur:
    name: "{{ item }}"
    dir:  "{{ xdg_cache_home }}/aur"
    user: "{{ ansible_user_id }}"
  with_items: "{{ aur_packages }}"
  become: true
