- name: "MacOS Homebrew : update package manager"
  homebrew:
    update_homebrew: yes

- name: "MacOS Homebrew : add taps"
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_taps }}"

- name: "MacOS Homebrew : update packages"
  homebrew:
    upgrade_all: yes
  when: package_upgrade

- name: "MacOS Homebrew : install packages"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_packages }}"

- name: "MacOS Homebrew : install Cask desktop apps"
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ cask_packages }}"
