- name: "Xresources : main"
  template:
    src: xresources.j2
    dest: "{{ xdg_config_home }}/xorg/Xresources"
  with_dict: "{{ palette }}"
  register: update_xresources

- name: "Xresources : ST"
  template:
    src: xresources_st.j2
    dest: "{{ xdg_config_home }}/xorg/Xresources.st"
  register: update_xresources

- name: "Xresources : rxvt-unicode"
  template:
    src: xresources_urxvt.j2
    dest: "{{ xdg_config_home }}/xorg/Xresources.urxvt"
  register: update_xresources

- name: "Xresources : Rofi"
  template:
    src: xresources_rofi.j2
    dest: "{{ xdg_config_home }}/xorg/Xresources.rofi"
  with_dict: "{{ palette }}"
  register: update_xresources

- name: "Xresources : reload database"
  command: "{{ xdg_config_home }}/xorg/Xprofile"
  when: update_xresources.changed

