- name: "Set locale"
  copy:
    src: locale
    dest: "{{ xdg_config_home }}/locale.conf"
    backup: yes

- name: "User fonts: directory"
  file:
    path: "{{ xdg_data_home }}/fonts"
    state: directory
    mode: 0755

- name: "Install Anonymice Powerline Nerd Font"
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/AnonymousPro/complete/Anonymice%20Powerline%20Nerd%20Font%20Complete%20Mono.ttf?raw=true"
    dest: "{{ xdg_data_home }}/fonts/AnonymousPro.ttf"
    checksum: sha256:6600d6e6a52a277ced42beb07fd30159847ec89462ff8cf9c221df0775412400
  register: install_font_linux

- name: "Update font cache"
  command: "fc-cache -f -v"
  when: install_font_linux.changed

- include: xorg.yml
  when: ansible_system == "Linux"
