- name: "Xorg: config directory"
  file:
    path: "{{ xdg_config_home }}/xorg"
    state: directory
    mode: 0700

- name: "Xorg: xinitrc"
  template:
    src: xorg/xinitrc.j2
    dest: "{{ ansible_user_dir }}/.xinitrc"

- name: "Xorg: Xprofile"
  template:
    src: xorg/xprofile.j2
    dest: "{{ xdg_config_home }}/xorg/Xprofile"

- name: "Xorg: Xresources"
  template:
    src: xorg/xresources.j2
    dest: "{{ xdg_config_home }}/xorg/Xresources"

- name: "Xorg: Rofi's Xresources"
  template:
    src: xorg/rofi_xresources.j2
    dest: "{{ xdg_config_home }}/xorg/Xresources.rofi"

- name: "Xorg: rxvt-unicode256's Xresources"
  template:
    src: xorg/urxvt256_xresources.j2
    dest: "{{ xdg_config_home }}/xorg/Xresources.urxvt256"

- name: "Compton: config directory"
  file:
    path: "{{ xdg_config_home }}/compton"
    state: directory
    mode: 0700

- name: "Compton: config file"
  copy:
    src: xorg/compton
    dest: "{{ xdg_config_home }}/compton/config"

- name: "i3: config directory"
  file:
    path: "{{ xdg_config_home }}/i3"
    state: directory
    mode: 0700

- name: "i3: config file"
  template:
    src: xorg/i3.j2
    dest: "{{ xdg_config_home }}/i3/config"

- name: "Polybar: config directory"
  file:
    path: "{{ xdg_config_home }}/polybar"
    state: directory
    mode: 0700

- name: "Polybar: config file"
  template:
    src: xorg/polybar.j2
    dest: "{{ xdg_config_home }}/polybar/config"

- name: "Polybar: WM launcher"
  template:
    src: xorg/polybar_launcher.j2
    dest: "{{ xdg_config_home }}/polybar/launcher"
    mode: 0700
