- name: "Neovim : config directory"
  file:
    path: "{{ xdg_config_home }}/nvim"
    state: directory
    mode: 0700

- name: "Neovim : autoload directory"
  file:
    path: "{{ xdg_data_home }}/nvim/site/autoload"
    state: directory
    mode: 0700

- name: "Neovim : download pathogen.vim"
  get_url:
    url: "{{ pathogen_vim_url }}"
    dest: "{{ xdg_data_home }}/nvim/site/autoload/pathogen.vim"
    checksum: "{{ pathogen_vim_sha }}"

- name: "Neovim : clone plugins"
  git:
    repo: "{{ item.url }}"
    dest: "{{ xdg_data_home }}/nvim/bundle/{{ item.dest }}"
  with_items: "{{ vim_plugins }}"

- name: "Neovim : config"
  template:
    src: neovim.j2
    dest: "{{ xdg_config_home }}/nvim/init.vim"

- name: "Neovim : colorscheme directory"
  file:
    path: "{{ xdg_data_home }}/nvim/bundle/colors"
    state: directory
    mode: 0700

- name: "Neovim : colorscheme"
  template:
    src: colorscheme.j2
    dest: "{{ xdg_data_home }}/nvim/bundle/colors/{{ vi_theme }}.vim"

- name: "Neovim : airline theme"
  template:
    src: airline.j2
    dest: "{{ xdg_data_home }}/nvim/bundle/vim-airline/autoload/airline/themes/{{ vi_theme }}.vim"

- name: "Neovim : promptline theme"
  template:
    src: promptline.j2
    dest: "{{ xdg_data_home }}/nvim/bundle/promptline.vim/autoload/promptline/themes/{{ vi_theme }}.vim"
