- name: "MacOS : Monospace font"
  get_url:
    url: "{{ monospace_font_url }}"
    dest: "{{ prefix }}/Library/Fonts/monospace.ttf"
    checksum: "{{ monospace_font_sha }}"
  register: install_font_macos
